name: rekomendasiin

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80
    environment:
      - DB_NAME=rekomendasiin
      - DB_USER=root
      - DB_PASS=good_password
      - DB_HOST=db

  db:
    image: mysql:8.4.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rekomendasiin
      MYSQL_ROOT_PASSWORD: good_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
